language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests.py
before_script: 
  - "psql -c 'create database maintraq;' -U postgres"
  - python migrations.py
script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
  - coveralls

after_sucess:
  - "coveralls"