FORMAT: 1A
HOST: http://127.0.0.1:5000

# Maintraq

Maintenance Tracker App is an app that gives users the ability to reach out to operations/repairs
department regarding repair or maintenance requests and monitor the status
of their request.

## Allowed HTTPs requests:
1.`POST` : To create resource  
2.`PUT` : Update resource  
3.`GET` : Get a resource or list of resource  

# Description Of Some Server Responses:
+ 200 `OK` - the request was successful (some API calls may return 201 instead).
+ 201 `Created` - the request was successful and a resource was created.
+ 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
+ 400 `Bad Request` - the request could not be understood or was missing required parameters.
+ 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
+ 403 `Forbidden` - access denied.404 Not Found - resource was not found.405 Method Not Allowed - requested method is not supported for resource.

## Register User [/api/v2/auth/register]

### Any user can register at this endpoint [POST]

+ Request (application/json)

        {
            "first_name": "Annie",
            "last_name": "Ndindi",
            "email": "ndindi@gmail.com",
            "password": "WEeu00t"

        }

+ Response 200 (application/json)

    + Headers


    + Body

            { "email": [
             "ronaldo@gmail.com"
               ],
               "first_name": [
                 "wayne"
                 ],
              "last_name": [
                 "rooney"
               ],
             "message": "User created!"
            }


           
  
            
         
+ Response 209 (application/json)

    + Headers


    + Body

            {
            "message": "Email already exists"
            }
           
                
            
                
    

## Login User [/api/v2/auth/login]
### Registered users can login [POST]

+ Request (application/json)

        {
            "email": "ndindi@gmail.com",
            "password": "WEeu00t"
        }

+ Response 200 (application/json)

    + Headers


    + Body

            {"auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzA5OTA3ODAsImlhdCI6MTUzMDk4NzE4MCwic3ViIjoicm9uYWxkb0BnbWFpbC5jb20iLCJ1c2VyX2lkIjo2LCJyb2xlIjowfQ.f4aNmkajno_TlJMrCv8eMMNhIaZyjGkMrZXiNJ6o2SQ",
              "message": "Login successful",
              "role": 0
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            "message": "Wrong password!"
            }

## Requests-users [/api/v2/Auth/request]
### User create request [POST]

+ Request (application/json)

        {"title" :"old repairz",
         "location":"Kisumu",
         "body":"need more repairs done"
        }

+ Response 201 (application/json)

    + Headers


    + Body

            {
            
              "message": "Created successfully",
              "request_title": [
             "old repairz"
                ]
            }
            
+ Response 209 (application/json)

    + Headers


    + Body

            {
            
              "message": "Title already exists"
            }
            
+ Response 400 (application/json)

    + Headers


    + Body

            {
            
              "message": "Title cannot be empty"
            }
            
### User view all requests [GET /api/v2/users/requests]

+ Response 200 (application/json)

    + Headers


    + Body

            [
              {
                "body": "need more repairs done",
                "id": 18,
                "location": "Kisumu",
                "status": "Pending",
                "title": "New repairs",
                "userid": 6
                },
                {
                    "body": "need more repairs done",
                    "id": 19,
                    "location": "Kisumu",
                    "status": "Pending",
                    "title": "New repairz",
                    "userid": 6
                },
                {
                    "body": "need more repairs done",
                    "id": 20,
                    "location": "Kisumu",
                    "status": "Pending",
                    "title": "old repairz",
                    "userid": 6
                }
            ]
            
## User Actions on One Request [/api/v2/users/requests/id]
### Get a request by id [GET]

+ Response 200 (application/json)

    + Headers


    + Body

            {
            
                "body": "need more repairs done",
                "id": 18,
                "location": "Kisumu",
                "status": "Pending",
                "title": "New repairs",
                "userid": 6
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
### Update a request [PUT]

+ Request (application/json)

        {"title" :"New repairs",
         "location":"Kisumu",
         "body":"need more repairs done"
        }

+ Response 201 (application/json)

+ Response 200 (application/json)

    + Headers


    + Body

            {
            
                "body": "need more repairs done",
                "id": 18,
                "location": "Kisumu",
                "status": "Pending",
                "title": "New repairs",
                "userid": 6
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
## Requests-Admin [/api/v2/requests]
## Admin Get All
### Admin get all requusts[GET]

+ Response 200 (application/json)

    + Headers


    + Body

            [
                {
                    "body": "Need help with my car",
                    "id": 1,
                    "location": "Kenya",
                    "status": "Pending",
                    "title": "maintenanc",
                    "userid": 4
                },
                {
                    "body": "jjj",
                    "id": 16,
                    "location": "",
                    "status": "Pending",
                    "title": "",
                    "userid": 2
                },
                {
                    "body": "Broken headlights",
                    "id": 17,
                    "location": "Embu",
                    "status": "Pending",
                    "title": "repairs",
                    "userid": 2
                },
                {
                    "body": "need more repairs done",
                    "id": 18,
                    "location": "Kisumu",
                    "status": "Pending",
                    "title": "New repairs",
                    "userid": 6
                },
                {
                    "body": "need more repairs done",
                    "id": 19,
                    "location": "Kisumu",
                    "status": "Pending",
                    "title": "New repairz",
                    "userid": 6
                },
                {
                    "body": "need more repairs done",
                    "id": 20,
                    "location": "Kisumu",
                    "status": "Pending",
                    "title": "old repairz",
                    "userid": 6
                }
            ]
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
+ Response 403 (application/json)

    + Headers


    + Body

            {
            
                "message": "Permission Denied"
            }
            
## Admin Approve Request [/api/v2/requests/id/approve]
### Admin approve request [PUT]
+ Response 200 (application/json)

    + Headers


    + Body

            {
            
                "id": 1,
                "message": "Request approved successfully"
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
+ Response 403 (application/json)

    + Headers
    



    + Body

            {
            
                "message": "Permission Denied"
            }
            
## Admin Disapprove Request [/api/v2/requests/id/disapprove]
### Admin disapprove request [PUT]

+ Response 200 (application/json)

    + Headers


    + Body

            {
            
                "id": 1,
                "message": "Request disapproved successfully"
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
+ Response 403 (application/json)

    + Headers
    



    + Body

            {
            
                "message": "Permission Denied"
            }
            
## Admin Resolve Request [/api/v2/requests/id/resolve]
### Admin resolve request [PUT]

+ Response 200 (application/json)

    + Headers


    + Body

            {
            
                "id": 1,
                "message": "Request resolved successfully"
            }
            
+ Response 401 (application/json)

    + Headers


    + Body

            {
            
                "message": "Token is missing! Login to get token."
            }
            
+ Response 403 (application/json)

    + Headers
    



    + Body

            {
            
                "message": "Permission Denied"
            }